### ISSUE TITLE
Host via GH Pages?

### ISSUE THREAD

**Issue by cvburgess** [wolfgang42/paper-hn#3]
Hey there! I love this project and im a huge e-ink fan.

Would you be interested in adding a hosted copy via github pages or accepting a PR to do so?

Running this locally is fine in most scenarios but i have some devices id like to point at a URL and I figure the free github hosting is as good as any other.

**Comment by wolfgang42** [comment]
Does https://www.wolfgangfaust.com/project/paper-hn/ not work for you for some reason? If not I'm happy to accept PRs for improvements but I’d like to make sure I understand the problem first.

While you’re here—out of curiosity, how did you find out about this project?

**Comment by cvburgess** [comment]
Oh silly me, i didnt see the link in the readme - that works perfectly.

I saw this on HN back when it was posted and bookmarked it for a day when i had some time!

Great work amigo.

**Comment by wolfgang42** [comment]
Glad it was an easy fix :)
